DROP DATABASE IF EXISTS `battle`;
CREATE DATABASE `battle`;
USE `battle`;
CREATE TABLE `game` (
	`GAME_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`active` BIT(1) NULL DEFAULT NULL,
	`turn` INT(11) NULL DEFAULT NULL,
	`winnerNumber` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`GAME_ID`),
	UNIQUE INDEX `GAME_ID` (`GAME_ID`)
);
CREATE TABLE `field` (
	`FIELD_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`GAME_ID` INT(11) NULL DEFAULT NULL,
	`idxf` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`FIELD_ID`),
	UNIQUE INDEX `FIELD_ID` (`FIELD_ID`),
	INDEX `FK5CEA0FA4763527C` (`GAME_ID`),
	CONSTRAINT `FK5CEA0FA4763527C` FOREIGN KEY (`GAME_ID`) REFERENCES `game` (`GAME_ID`)
);
CREATE TABLE `shot` (
	`SHOT_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`x` INT(11) NULL DEFAULT NULL,
	`y` INT(11) NULL DEFAULT NULL,
	`FIELD_ID` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`SHOT_ID`),
	UNIQUE INDEX `SHOT_ID` (`SHOT_ID`),
	INDEX `FK35DAFAD70B19B8` (`FIELD_ID`),
	CONSTRAINT `FK35DAFAD70B19B8` FOREIGN KEY (`FIELD_ID`) REFERENCES `field` (`FIELD_ID`)
);
CREATE TABLE `field_shot` (
	`field_FIELD_ID` INT(11) NOT NULL,
	`shots_SHOT_ID` INT(11) NOT NULL,
	UNIQUE INDEX `shots_SHOT_ID` (`shots_SHOT_ID`),
	INDEX `FK22617F1F7B0DF7F6` (`shots_SHOT_ID`),
	INDEX `FK22617F1FF4CE235D` (`field_FIELD_ID`),
	CONSTRAINT `FK22617F1F7B0DF7F6` FOREIGN KEY (`shots_SHOT_ID`) REFERENCES `shot` (`SHOT_ID`),
	CONSTRAINT `FK22617F1FF4CE235D` FOREIGN KEY (`field_FIELD_ID`) REFERENCES `field` (`FIELD_ID`)
);
CREATE TABLE `ship` (
	`SHIP_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`length` INT(11) NULL DEFAULT NULL,
	`orientation` INT(11) NULL DEFAULT NULL,
	`wounds` INT(11) NULL DEFAULT NULL,
	`x` INT(11) NULL DEFAULT NULL,
	`y` INT(11) NULL DEFAULT NULL,
	`FIELD_ID` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`SHIP_ID`),
	UNIQUE INDEX `SHIP_ID` (`SHIP_ID`),
	INDEX `FK35DA3CD70B19B8` (`FIELD_ID`),
	CONSTRAINT `FK35DA3CD70B19B8` FOREIGN KEY (`FIELD_ID`) REFERENCES `field` (`FIELD_ID`)
);
CREATE TABLE `field_ship` (
	`field_FIELD_ID` INT(11) NOT NULL,
	`ships_SHIP_ID` INT(11) NOT NULL,
	UNIQUE INDEX `ships_SHIP_ID` (`ships_SHIP_ID`),
	INDEX `FK22617E612C35A3B4` (`ships_SHIP_ID`),
	INDEX `FK22617E61F4CE235D` (`field_FIELD_ID`),
	CONSTRAINT `FK22617E612C35A3B4` FOREIGN KEY (`ships_SHIP_ID`) REFERENCES `ship` (`SHIP_ID`),
	CONSTRAINT `FK22617E61F4CE235D` FOREIGN KEY (`field_FIELD_ID`) REFERENCES `field` (`FIELD_ID`)
);
CREATE TABLE `user` (
	`User_Type` VARCHAR(31) NOT NULL,
	`USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`login` VARCHAR(255) NULL DEFAULT NULL,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`password` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`USER_ID`),
	UNIQUE INDEX `USER_ID` (`USER_ID`),
	UNIQUE INDEX `login` (`login`)
);
CREATE TABLE `game_user` (
	`games_GAME_ID` INT(11) NOT NULL,
	`players_USER_ID` INT(11) NOT NULL,
	`idxu` INT(11) NOT NULL,
	PRIMARY KEY (`games_GAME_ID`, `idxu`),
	INDEX `FK3BACFFF894B62E4F` (`players_USER_ID`),
	INDEX `FK3BACFFF81611DAFE` (`games_GAME_ID`),
	CONSTRAINT `FK3BACFFF81611DAFE` FOREIGN KEY (`games_GAME_ID`) REFERENCES `game` (`GAME_ID`),
	CONSTRAINT `FK3BACFFF894B62E4F` FOREIGN KEY (`players_USER_ID`) REFERENCES `user` (`USER_ID`)
);
CREATE TABLE `invitation` (
	`INVITATION_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`inviter_USER_ID` INT(11) NULL DEFAULT NULL,
	`target_USER_ID` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`INVITATION_ID`),
	UNIQUE INDEX `INVITATION_ID` (`INVITATION_ID`),
	INDEX `FK473F7799B67E5826` (`inviter_USER_ID`),
	INDEX `FK473F7799741D8F2E` (`target_USER_ID`),
	CONSTRAINT `FK473F7799741D8F2E` FOREIGN KEY (`target_USER_ID`) REFERENCES `user` (`USER_ID`),
	CONSTRAINT `FK473F7799B67E5826` FOREIGN KEY (`inviter_USER_ID`) REFERENCES `user` (`USER_ID`)
);

INSERT INTO `user` (`User_Type`, `name`, `login`, `password`) VALUES ('Admin', 'admin', 'admin','admin');